IngressoMVC/Controllers/AtoresController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using IngressoMVC.Models.ViewModels.ResponseDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class AtoresController : Controller
    {
        private IngressoDbContext _context;

        public AtoresController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Atores);
        }

        public IActionResult Detalhes(int id)
        {
            var resultado = _context.Atores
                .Include(af => af.AtoresFilmes)
                .ThenInclude(f => f.Filme)
                .FirstOrDefault(ator => ator.Id == id);

            if (resultado == null)
                return View("NotFound");           

            return View(resultado);
        }

        public IActionResult Criar() => View();

        [HttpPost]
        public IActionResult Criar(PostAtorDTO atorDto)
        {
            if (!ModelState.IsValid)
                return View(atorDto);

            Ator ator = new Ator(atorDto.Nome, atorDto.Bio, atorDto.FotoPerfilURL);
            _context.Atores.Add(ator);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int? id)
        {
            if (id == null)
                return NotFound();

            var result = _context.Atores.FirstOrDefault(a => a.Id == id);

            if (result == null)
                return View();

            return View(result);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostAtorDTO atorDto)
        {
            var ator = _context.Atores.FirstOrDefault(a => a.Id == id);

            if (!ModelState.IsValid)
                return View(ator);

            ator.AtualizarDados(atorDto.Nome, atorDto.Bio, atorDto.FotoPerfilURL);

            _context.Update(ator);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Atores.FirstOrDefault(a => a.Id == id);

            if (result == null) return View();

            return View(result);
        }

        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Atores.FirstOrDefault(a => a.Id == id);
            _context.Atores.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

IngressoMVC/Controllers/CategoriasController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class CategoriasController : Controller
    {
        private IngressoDbContext _context;

        public CategoriasController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index() => View(_context.Categorias);

        public IActionResult Detalhes(int id) => View(_context.Categorias.Find(id));

        public IActionResult Criar() => View();

        [HttpPost]
        public IActionResult Criar(PostCategoriaDTO categoriaDto)
        {
            if(!ModelState.IsValid) return View(categoriaDto);
            Categoria categoria = new Categoria(categoriaDto.Nome);
            _context.Add(categoria);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int? id)
        {
            if (id == null) return NotFound();

            var result = _context.Categorias.FirstOrDefault(a => a.Id == id);

            if (result == null) return View();          
            
            return View(result);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostCategoriaDTO categoriaDto)
        {
            var result = _context.Categorias.FirstOrDefault(a => a.Id == id);

            if (!ModelState.IsValid) return View(result);

            result.AtualizarDados(categoriaDto.Nome);
            _context.Categorias.Update(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Categorias.FirstOrDefault(a => a.Id == id);
            if (result == null) return View();
            return View(result);
        }

        [HttpPost]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Categorias.FirstOrDefault(a => a.Id == id);
            _context.Categorias.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

IngressoMVC/Controllers/CinemasController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class CinemasController : Controller
    {
        private IngressoDbContext _context;

        public CinemasController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Cinemas);
        }

        public IActionResult Detalhes(int id)
        {
            var cinema = _context.Cinemas
                .Include(c => c.Filmes)
                .FirstOrDefault(c => c.Id == id);

            if (cinema == null)
                return View("NotFound");

            return View(cinema);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(PostCinemaDTO cinemaDto)
        {
            if (!ModelState.IsValid) return View(cinemaDto);

            Cinema cinema = new Cinema(cinemaDto.Nome, cinemaDto.Descricao, cinemaDto.LogoURL);
            _context.Cinemas.Add(cinema);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int id)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);

            if (result == null)
                return View("NotFound");

            return View(result);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostCinemaDTO cinemaDTO)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);
            result.AtualizarDados(cinemaDTO.Nome, cinemaDTO.Descricao, cinemaDTO.LogoURL);
            _context.Cinemas.Update(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);

            if (result == null)
            {
                return View("NotFound");
            }

            return View(result);
        }

        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);
            if (result == null)
                return View("NotFound");

            _context.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

IngressoMVC/Controllers/FilmesController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class FilmesController : Controller
    {
        private IngressoDbContext _context;

        public FilmesController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index() => View(_context.Filmes);

        public IActionResult Criar()
        {
            DadosDropdown();

            return View();
        }

        [HttpPost]
        public IActionResult Criar(PostFilmeDTO filmeDto)
        {
            if (!ModelState.IsValid)
            {
                DadosDropdown();
                return View();
            }

            Filme filme = new Filme
                (
                    filmeDto.Titulo,
                    filmeDto.Descricao,
                    filmeDto.Preco,
                    filmeDto.ImagemURL,
                    filmeDto.ProdutorId,
                    filmeDto.CinemaId,
                    filmeDto.DataLancamento,
                    filmeDto.DataEncerramento
                );

            _context.Add(filme);
            _context.SaveChanges();

            foreach (var categoriaId in filmeDto.CategoriasId)
            {
                var novaCategoria = new FilmeCategoria(filme.Id, categoriaId);
                _context.FilmesCategorias.Add(novaCategoria);
                _context.SaveChanges();
            }

            foreach (var atorId in filmeDto.AtoresId)
            {
                var novoAtor = new AtorFilme(atorId, filme.Id);
                _context.AtoresFilmes.Add(novoAtor);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int id)
        {
            var result = _context.Filmes
                .Include(x => x.AtoresFilmes).ThenInclude(x => x.Ator)
                .Include(x => x.FilmesCategorias).ThenInclude(x => x.Categoria)
                .FirstOrDefault(x => x.Id == id);

            if (result == null)
                return View("NotFound");

            var response = new PostFilmeDTO()
            {
                Titulo = result.Titulo,
                Descricao = result.Descricao,
                Preco = result.Preco,
                ImagemURL = result.ImagemURL,
                DataLancamento = result.DataLancamento,
                DataEncerramento = result.DataEncerramento,
                CinemaId = result.CinemaId,
                ProdutorId = result.ProdutorId,
                AtoresId = result.AtoresFilmes.Select(x => x.AtorId).ToList(),
                CategoriasId = result.FilmesCategorias.Select(x => x.CategoriaId).ToList()
            };

            DadosDropdown();
            return View(response);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostFilmeDTO filmeDto)
        {
            var result = _context.Filmes.FirstOrDefault(x => x.Id == id);

            if (!ModelState.IsValid)
            {
                DadosDropdown();
                return View(result);
            }

            result.AlterarDados
                (
                filmeDto.Titulo,
                filmeDto.Descricao,
                filmeDto.Preco,
                filmeDto.ImagemURL,
                filmeDto.ProdutorId,
                filmeDto.CinemaId,
                filmeDto.DataEncerramento,
                filmeDto.DataEncerramento
                );

            _context.Update(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Detalhes), result);
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Filmes.FirstOrDefault(x => x.Id == id);

            if (result == null)
                return View("NotFound");

            return View(result);
        }

        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Filmes.FirstOrDefault(x => x.Id == id);

            _context.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(int id)
        {
            var result = _context.Filmes
                .Include(p => p.Produtor)
                .Include(c => c.Cinema)
                .Include(fc => fc.FilmesCategorias).ThenInclude(c => c.Categoria)
                .Include(af => af.AtoresFilmes).ThenInclude(a => a.Ator)
                .FirstOrDefault(f => f.Id == id);

            return View(result);
        }

        public void DadosDropdown()
        {
            var resp = new PostFilmeDropdownDTO()
            {
                Atores = _context.Atores.OrderBy(x => x.Nome).ToList(),
                Categorias = _context.Categorias.OrderBy(x => x.Nome).ToList(),
                Cinemas = _context.Cinemas.OrderBy(x => x.Nome).ToList(),
                Produtores = _context.Produtores.OrderBy(x => x.Nome).ToList()
            };

            ViewBag.Atores = new SelectList(resp.Atores, "Id", "Nome");
            ViewBag.Categorias = new SelectList(resp.Categorias, "Id", "Nome");
            ViewBag.Cinemas = new SelectList(resp.Cinemas, "Id", "Nome");
            ViewBag.Produtores = new SelectList(resp.Produtores, "Id", "Nome");
        }

            public IActionResult Buscar(string FiltroDeBusca)
            {
                var result = _context.Filmes
                .Include(filme => filme.AtoresFilmes).ThenInclude(af => af.Ator)
                .ToList();

                if(!string.IsNullOrEmpty(FiltroDeBusca))
                {
                FiltroDeBusca = FiltroDeBusca.ToLower();
                var resultadoDaBusca = result
                    .Where(x => x.Titulo.ToLower().Contains(FiltroDeBusca) || x.Descricao.ToLower().Contains(FiltroDeBusca) || x.AtoresFilmes
                    .Select(af=>af.Ator.Nome.ToLower().Contains(FiltroDeBusca)).FirstOrDefault())
                    .ToList();
                return View(nameof(Index), resultadoDaBusca);
                }
            return View(nameof(Index), result);
            }
        }
    }

IngressoMVC/Views/Shared/NotFound.cshtml
<h1>NÃO ENCONTRADO</h1>
<img src="https://th.bing.com/th/id/R.ab99060304a8651eddda801dd8443975?rik=Oak2cYx32%2fywNQ&pid=ImgRaw&r=0">

IngressoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ingresso Clone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Filmes" asp-action="Index"><i class="fa-solid fa-film"></i> Filmes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Filmes" asp-action="Index"><i class="fa-solid fa-film"></i> Filmes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Atores" asp-action="Index"><i class="fa-solid fa-users-rectangle"></i> Atores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Cinemas" asp-action="Index"><i class="fa-regular fa-tape"></i> Cinemas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Produtores" asp-action="Index"><i class="fa-solid fa-address-card"></i> Produtores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Categorias" asp-action="Index"><i class="fa-solid fa-clipboard-question"></i>Categorias</a>
                        </li>
                    </ul>
                </div>
                <form class="form-inline my-2 my-lg-0" asp-controller="Filmes" asp-action="Buscar">
                    <input class="form-control" name="FiltroDeBusca" type="text" placeholder="Buscar filmes...">
                    <button class="btn btn-primary my-2 my-sm-0 mf-1" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IngressoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IngressoMVC/Views/Shared/_NovoItem.cshtml
@model string

<div class="row">
    <a asp-action="Criar" class="btn btn-lg btn-block btn-primary">
        <i class="fa-solid fa-circle-plus"></i> Adicionar @Model
    </a>
</div>