IngressoMVC/Models/Filme.cs
using IngressoMVC.Models.Interfaces;
using System;
using System.Collections.Generic;

namespace IngressoMVC.Models
{
    public class Filme : IEntidade
    {
        protected Filme()
        {

        }

        public Filme(string titulo, string descricao, decimal preco, string imageURL, int produtorId, 
                     int cinemaId, DateTime lancamento, DateTime encerramento)
        {
            Titulo = titulo;
            Descricao = descricao;
            Preco = preco;
            ImagemURL = imageURL;
            ProdutorId = produtorId;
            CinemaId = cinemaId;
            DataLancamento = lancamento;
            DataEncerramento = encerramento;

            DataCadastro = DateTime.Now;
            DataAlteracao = DataCadastro;            
        }

        public int Id { get; private set; }
        public DateTime DataCadastro { get; private set; }
        public DateTime DataAlteracao { get; private set; }
        public string Titulo { get; private set; }
        public string Descricao { get; private set; }
        public decimal Preco { get; private set; }
        public string ImagemURL { get; private set; }

        public DateTime DataLancamento { get; private set; }
        public DateTime DataEncerramento { get; private set; }

        #region relacionamentos
        public int CinemaId { get; set; }
        public Cinema Cinema { get; set; }

        public int ProdutorId { get; set; }
        public Produtor Produtor { get; set; }

        public List<AtorFilme> AtoresFilmes { get; set; }
        public List<FilmeCategoria> FilmesCategorias { get; set; }
        #endregion


        public void AlterarDados(string titulo, string descricao, decimal novoPreco, string imagem, int produtorId, 
                                int cinemaId, DateTime lancamento, DateTime encerramento)
        {
            if (titulo.Length < 1 || novoPreco < 0)
                return;
            Titulo = titulo;
            Descricao = descricao;
            Preco = novoPreco;
            ImagemURL = imagem;
            ProdutorId = produtorId;
            CinemaId = cinemaId;
            DataLancamento = lancamento;
            DataEncerramento = encerramento;

            DataAlteracao = DateTime.Now;
        }
    }
}

IngressoMVC/Controllers/AtoresController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using IngressoMVC.Models.ViewModels.ResponseDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class AtoresController : Controller
    {
        private IngressoDbContext _context;

        public AtoresController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Atores);
        }

        public IActionResult Detalhes(int id)
        {
            var resultado = _context.Atores
                .Include(af => af.AtoresFilmes)
                .ThenInclude(f => f.Filme)
                .FirstOrDefault(ator => ator.Id == id);

            if (resultado == null)
                return View("NotFound");           

            return View(resultado);
        }

        public IActionResult Criar() => View();

        [HttpPost]
        public IActionResult Criar(PostAtorDTO atorDto)
        {
            if (!ModelState.IsValid)
                return View(atorDto);

            Ator ator = new Ator(atorDto.Nome, atorDto.Bio, atorDto.FotoPerfilURL);
            _context.Atores.Add(ator);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int? id)
        {
            if (id == null)
                return NotFound();

            var result = _context.Atores.FirstOrDefault(a => a.Id == id);

            if (result == null)
                return View();

            return View(result);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostAtorDTO atorDto)
        {
            var ator = _context.Atores.FirstOrDefault(a => a.Id == id);

            if (!ModelState.IsValid)
                return View(ator);

            ator.AtualizarDados(atorDto.Nome, atorDto.Bio, atorDto.FotoPerfilURL);

            _context.Update(ator);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Atores.FirstOrDefault(a => a.Id == id);

            if (result == null) return View();

            return View(result);
        }

        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Atores.FirstOrDefault(a => a.Id == id);
            _context.Atores.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

IngressoMVC/Controllers/CinemasController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class CinemasController : Controller
    {
        private IngressoDbContext _context;

        public CinemasController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Cinemas);
        }

        public IActionResult Detalhes(int id)
        {
            var cinema = _context.Cinemas
                .Include(c => c.Filmes)
                .FirstOrDefault(c => c.Id == id);

            if (cinema == null)
                return View("NotFound");

            return View(cinema);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(PostCinemaDTO cinemaDto)
        {
            if (!ModelState.IsValid) return View(cinemaDto);

            Cinema cinema = new Cinema(cinemaDto.Nome, cinemaDto.Descricao, cinemaDto.LogoURL);
            _context.Cinemas.Add(cinema);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int id)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);

            if (result == null)
                return View("NotFound");

            return View(result);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostCinemaDTO cinemaDTO)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);
            result.AtualizarDados(cinemaDTO.Nome, cinemaDTO.Descricao, cinemaDTO.LogoURL);
            _context.Cinemas.Update(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);

            if (result == null)
            {
                return View("NotFound");
            }

            return View(result);
        }

        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Cinemas.FirstOrDefault(cinema => cinema.Id == id);
            if (result == null)
                return View("NotFound");

            _context.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

IngressoMVC/Controllers/FilmesController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class FilmesController : Controller
    {
        private IngressoDbContext _context;

        public FilmesController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index() => View(_context.Filmes);

        public IActionResult Criar()
        {
            DadosDropdown();

            return View();
        }

        [HttpPost]
        public IActionResult Criar(PostFilmeDTO filmeDto)
        {
            if (!ModelState.IsValid)
            {
                DadosDropdown();
                return View();
            }

            Filme filme = new Filme
                (
                    filmeDto.Titulo,
                    filmeDto.Descricao,
                    filmeDto.Preco,
                    filmeDto.ImagemURL,
                    filmeDto.ProdutorId,
                    filmeDto.CinemaId,
                    filmeDto.DataLancamento,
                    filmeDto.DataEncerramento
                );

            _context.Add(filme);
            _context.SaveChanges();

            foreach (var categoriaId in filmeDto.CategoriasId)
            {
                var novaCategoria = new FilmeCategoria(filme.Id, categoriaId);
                _context.FilmesCategorias.Add(novaCategoria);
                _context.SaveChanges();
            }

            foreach (var atorId in filmeDto.AtoresId)
            {
                var novoAtor = new AtorFilme(atorId, filme.Id);
                _context.AtoresFilmes.Add(novoAtor);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int id)
        {
            var result = _context.Filmes
                .Include(x => x.AtoresFilmes).ThenInclude(x => x.Ator)
                .Include(x => x.FilmesCategorias).ThenInclude(x => x.Categoria)
                .FirstOrDefault(x => x.Id == id);

            if (result == null)
                return View("NotFound");

            var response = new PostFilmeDTO()
            {
                Titulo = result.Titulo,
                Descricao = result.Descricao,
                Preco = result.Preco,
                ImagemURL = result.ImagemURL,
                DataLancamento = result.DataLancamento,
                DataEncerramento = result.DataEncerramento,
                CinemaId = result.CinemaId,
                ProdutorId = result.ProdutorId,
                AtoresId = result.AtoresFilmes.Select(x => x.AtorId).ToList(),
                CategoriasId = result.FilmesCategorias.Select(x => x.CategoriaId).ToList()
            };

            DadosDropdown();
            return View(response);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostFilmeDTO filmeDto)
        {
            var result = _context.Filmes.FirstOrDefault(x => x.Id == id);

            if (!ModelState.IsValid)
            {
                DadosDropdown();
                return View(result);
            }

            result.AlterarDados
                (
                filmeDto.Titulo,
                filmeDto.Descricao,
                filmeDto.Preco,
                filmeDto.ImagemURL,
                filmeDto.ProdutorId,
                filmeDto.CinemaId,
                filmeDto.DataEncerramento,
                filmeDto.DataEncerramento
                );

            _context.Update(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Detalhes), result);
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Filmes.FirstOrDefault(x => x.Id == id);

            if (result == null)
                return View("NotFound");

            return View(result);
        }

        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Filmes.FirstOrDefault(x => x.Id == id);

            _context.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(int id)
        {
            var result = _context.Filmes
                .Include(p => p.Produtor)
                .Include(c => c.Cinema)
                .Include(fc => fc.FilmesCategorias).ThenInclude(c => c.Categoria)
                .Include(af => af.AtoresFilmes).ThenInclude(a => a.Ator)
                .FirstOrDefault(f => f.Id == id);

            return View(result);
        }

        public void DadosDropdown()
        {
            var resp = new PostFilmeDropdownDTO()
            {
                Atores = _context.Atores.OrderBy(x => x.Nome).ToList(),
                Categorias = _context.Categorias.OrderBy(x => x.Nome).ToList(),
                Cinemas = _context.Cinemas.OrderBy(x => x.Nome).ToList(),
                Produtores = _context.Produtores.OrderBy(x => x.Nome).ToList()
            };

            ViewBag.Atores = new SelectList(resp.Atores, "Id", "Nome");
            ViewBag.Categorias = new SelectList(resp.Categorias, "Id", "Nome");
            ViewBag.Cinemas = new SelectList(resp.Cinemas, "Id", "Nome");
            ViewBag.Produtores = new SelectList(resp.Produtores, "Id", "Nome");
        }

            public IActionResult Buscar(string FiltroDeBusca)
            {
                var result = _context.Filmes
                .Include(filme => filme.AtoresFilmes).ThenInclude(af => af.Ator)
                .ToList();

                if(!string.IsNullOrEmpty(FiltroDeBusca))
                {
                FiltroDeBusca = FiltroDeBusca.ToLower();
                var resultadoDaBusca = result
                    .Where(x => x.Titulo.ToLower().Contains(FiltroDeBusca) || x.Descricao.ToLower().Contains(FiltroDeBusca) || x.AtoresFilmes
                    .Select(af=>af.Ator.Nome.ToLower().Contains(FiltroDeBusca)).FirstOrDefault())
                    .ToList();
                return View(nameof(Index), resultadoDaBusca);
                }
            return View(nameof(Index), result);
            }
        }
    }

IngressoMVC/Controllers/ProdutoresController.cs
using IngressoMVC.Data;
using IngressoMVC.Models;
using IngressoMVC.Models.ViewModels.RequestDTO;
using IngressoMVC.Models.ViewModels.ResponseDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace IngressoMVC.Controllers
{
    public class ProdutoresController : Controller
    {
        private IngressoDbContext _context;

        public ProdutoresController(IngressoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index() => View(_context.Produtores);

        public IActionResult Detalhes(int id)
        {
            var resultado = _context.Produtores.Include(p => p.Filmes).FirstOrDefault(p => p.Id == id);

            if (resultado == null)
                return View("NotFound");            

            return View(resultado);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(PostProdutorDTO produtorDto)
        {
            if(!ModelState.IsValid)
                return View(produtorDto);

            Produtor produtor = new Produtor(
                produtorDto.Nome, 
                produtorDto.Bio, 
                produtorDto.FotoPerfilURL);

            _context.Produtores.Add(produtor);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Atualizar(int? id)
        {
            if(id == null)
                return NotFound();

            var result = _context.Produtores.FirstOrDefault(p => p.Id == id);
            
            if(result == null)
                return View();

            return View(result);
        }

        [HttpPost]
        public IActionResult Atualizar(int id, PostProdutorDTO produtorDTO)
        {
            var produtor = _context.Produtores.FirstOrDefault(p => p.Id == id);

            if(!ModelState.IsValid)
                return View(produtor);

            produtor.AtualizarDados(produtorDTO.Nome, produtorDTO.Bio, produtorDTO.FotoPerfilURL);

            _context.Update(produtor);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Deletar(int id)
        {
            var result = _context.Produtores.FirstOrDefault(p => p.Id == id);

            if(result == null)
                return View();

            return View(result);
        }

        [HttpPost]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Produtores.FirstOrDefault(p => p.Id == id);
            
            _context.Produtores.Remove(result);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

IngressoMVC/Views/Filmes/Atualizar.cshtml
@model IngressoMVC.Models.ViewModels.RequestDTO.PostFilmeDTO

@{
    ViewData["Title"] = "Cadastrar Filme";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Atualizar Filme</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Atualizar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Titulo" class="control-label"></label>
                                <input asp-for="Titulo" class="form-control" />
                                <span asp-validation-for="Titulo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DataLancamento" class="control-label"></label>
                                <input asp-for="DataLancamento" type="date" class="form-control" />
                                <span asp-validation-for="DataLancamento" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DataEncerramento" class="control-label"></label>
                                <input asp-for="DataEncerramento" type="date" class="form-control" />
                                <span asp-validation-for="DataEncerramento" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Preco" class="control-label"></label>
                                <input asp-for="Preco" type="number" class="form-control" />
                                <span asp-validation-for="Preco" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImagemURL" class="control-label"></label>
                                <input asp-for="ImagemURL" class="form-control" />
                                <span asp-validation-for="ImagemURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoriasId" class="control-label"></label>
                                <select asp-for="CategoriasId" class="form-control" asp-items="ViewBag.Categorias" multiple></select>
                                <span asp-validation-for="CategoriasId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProdutorId" class="control-label"></label>
                                <select asp-for="ProdutorId" class="form-control" asp-items="ViewBag.Produtores"></select>
                                <span asp-validation-for="ProdutorId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AtoresId" class="control-label"></label>
                                <select asp-for="AtoresId" class="form-control" asp-items="ViewBag.Atores" multiple></select>
                                <span asp-validation-for="AtoresId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Descricao" class="control-label"></label>
                                <textarea asp-for="Descricao" class="form-control"></textarea>
                                <span asp-validation-for="Descricao" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Atualizar" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Mostrar Todos</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

IngressoMVC/Views/Filmes/Deletar.cshtml
@model Filme

@{
    ViewData["Title"] = "Deletar Filme";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Deletar Ator @Model.Titulo</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">                
                    <div class="form-group">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Descricao" class="control-label"></label>
                        <input asp-for="Descricao" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ImagemURL" class="control-label"></label>
                        <input asp-for="ImagemURL" class="form-control" />
                    </div>

                    <div class="form-group">
                        <form asp-action="Deletar">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Confirmar" class="btn btn-outline-danger float-right" />
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Listar Todos</a>
                    </div>
                    
            </div>
        </div>
    </div>
</div>

IngressoMVC/Views/Filmes/Detalhes.cshtml
@model Filme

@{
    ViewData["Title"] = "Movie details";
}

<div class="row">
    <div class="col-md-8">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Titulo
                                <a class="text-white float-right" asp-action="Atualizar" asp-route-id="@Model.Id"><i class="fa-regular fa-pen-to-square"></i></a>
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImagemURL" width="100%" alt="@Model.Titulo">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Descricao</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinemas" asp-action="Detalhes" asp-route-id="@Model.CinemaId">
                                @Model.Cinema.Nome
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Produtor: </b>
                            <a asp-controller="Produtores" asp-action="Detalhes" asp-route-id="@Model.ProdutorId">
                                @Model.Produtor.Nome
                            </a>
                        </p>
                        <p class="card-text"><b>Estréia: </b>@Model.DataLancamento.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>Até: </b>@Model.DataEncerramento.ToString("dd MMM yy")</p>
                        <p>
                            <b>Situação: </b>                           
                            @if (DateTime.Now >= Model.DataLancamento && DateTime.Now <= Model.DataEncerramento)
                            {
                                <span class="badge bg-success text-white">DISPONÍVEL</span>
                            }
                            else if (DateTime.Now > Model.DataEncerramento)
                            {
                                <span class="badge bg-danger text-white"><i class="fa-solid fa-hourglass"></i>EXPIRADO</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">AGUARDANDO</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Atores: </b>
                            <hr />
                            <div class="row">
                                @foreach (var atore_filme in Model.AtoresFilmes)
                                {
                                    <div class="column text-center">
                                        <img src="@atore_filme.Ator.FotoPerfilURL" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Atores" asp-action="Detalhes" asp-route-id="@atore_filme.Ator.Id">@atore_filme.Ator.Nome</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Lista de Filmes
                            </a>
                            <a class="btn btn-success text-white  @((DateTime.Now > Model.DataEncerramento) ? "disabled" : "")" 
                               asp-controller="Pedidos" 
                               asp-action="AdicionarCarrinho" asp-route-id="@Model.Id">
                               <i class="fa-solid fa-cart-arrow-down"></i> Adicionar (@Model.Preco.ToString("c"))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

IngressoMVC/Views/Filmes/Index.cshtml
@model IEnumerable<Filme>

@{
    ViewData["Title"] = "Lista de Filmes";
}

@*@Html.Partial("_NovoItem", "Filme")*@
<partial name="_NovoItem" model="nameof(Filme)"/>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Titulo
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <a asp-action="Detalhes" asp-route-id="@item.Id"><img src="@item.ImagemURL" width="100%" alt="@item.Titulo"></a>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>Estréia: </b>@item.DataLancamento.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>Até: </b>@item.DataEncerramento.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Situação: </b>
                                @if (DateTime.Now >= item.DataLancamento && DateTime.Now <= item.DataEncerramento)
                                {
                                    <span class="badge bg-success text-white">DISPONÍVEL</span>
                                }
                                else if (DateTime.Now > item.DataEncerramento)
                                {
                                    <span class="badge bg-danger text-white"><i class="fa-solid fa-hourglass"></i> EXPIRADO</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">AGUARDANDO</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Detalhes" asp-route-id="@item.Id">
                                    <i class="fa-solid fa-eye"></i> Detalhes
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.DataEncerramento) ? "disabled" : "")"
                               asp-controller="Pedidos"
                               asp-action="AdicionarCarrinho"
                               asp-route-id="@item.Id">
                                    <i class="fa-solid fa-cart-arrow-down"></i> Adicionar (@item.Preco.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>